# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/construction_cost_risk_analysis',
                'doc_host': 'https://justforprogramming07-code.github.io',
                'git_url': 'https://github.com/justforprogramming07-code/construction_cost_risk_analysis',
                'lib_path': 'construction_cost_risk_analysis'},
  'syms': { 'construction_cost_risk_analysis.core': { 'construction_cost_risk_analysis.core.foo': ( 'core.html#foo',
                                                                                                    'construction_cost_risk_analysis/core.py')}}}
